Traceback (most recent call last):
  File "/home/thiagorr/.cache/pypoetry/virtualenvs/prog-stat-5bravkBa-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/thiagorr/.cache/pypoetry/virtualenvs/prog-stat-5bravkBa-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/thiagorr/.cache/pypoetry/virtualenvs/prog-stat-5bravkBa-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/thiagorr/.cache/pypoetry/virtualenvs/prog-stat-5bravkBa-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/thiagorr/.cache/pypoetry/virtualenvs/prog-stat-5bravkBa-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/thiagorr/.cache/pypoetry/virtualenvs/prog-stat-5bravkBa-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Importando bibliotecas
import seaborn as sns
import pandas as pd

# Carregando o dataset Iris
iris = sns.load_dataset('iris')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;66;03m# Importando bibliotecas[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mseaborn[39;00m [38;5;28;01mas[39;00m [38;5;21;01msns[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m      5[0m [38;5;66;03m# Carregando o dataset Iris[39;00m

[0;31mModuleNotFoundError[0m: No module named 'seaborn'

